/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ucmmaster.kafka.data.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Información estática de cada dispositivo */
@org.apache.avro.specific.AvroGenerated
public class Device extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7887420172700212222L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Device\",\"namespace\":\"com.ucmmaster.kafka.data.v1\",\"doc\":\"Información estática de cada dispositivo\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"int\",\"arg.properties\":{\"iteration\":{\"start\":1,\"step\":1,\"max\":100}}},\"doc\":\"Device id\"},{\"name\":\"serial\",\"type\":{\"type\":\"string\",\"arg.properties\":{\"regex\":\"SN[A-Z0-9]{8}\"}},\"doc\":\"Numero de serie\"},{\"name\":\"firmware\",\"type\":{\"type\":\"string\",\"default\":\"v1.0.0\",\"arg.properties\":{\"options\":[\"v1.2.3\",\"v1.3.1\",\"v2.0.0-beta\",\"v2.1.4\",\"v3.0.0\"]}},\"doc\":\"Versión del firmware\"},{\"name\":\"model\",\"type\":{\"type\":\"string\",\"arg.properties\":{\"options\":[\"TEMP-SENSOR-PRO\",\"ENV-MONITOR-3000\",\"CLIMATE-GUARD-X1\",\"SMART-THERMO-V2\",\"IoT-CLIMA-LITE\"]}},\"doc\":\"Modelo de dispositivo\"},{\"name\":\"temperature_threshold\",\"type\":{\"type\":\"int\",\"arg.properties\":{\"range\":{\"min\":35,\"max\":40}}},\"doc\":\"Temperatura umbral crítica\"},{\"name\":\"latitude\",\"type\":{\"type\":\"double\",\"arg.properties\":{\"options\":[52.52,48.86,51.51,41.39,48.21,59.44,52.23,50.85,55.76,38.72,44.84,37.98,42.7,50.08,53.35]}},\"doc\":\"Latitud en grados decimales (WGS 84 / EPSG:4326)\"},{\"name\":\"longitude\",\"type\":{\"type\":\"double\",\"arg.properties\":{\"options\":[13.41,2.35,-0.13,-2.17,16.37,24.75,21.01,4.35,37.62,-9.14,20.47,23.72,23.32,4.35,-6.26]}},\"doc\":\"Longitud en grados decimales (WGS 84 / EPSG:4326)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Device> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Device> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Device> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Device> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Device> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Device to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Device from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Device instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Device fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device id */
  private int id;
  /** Numero de serie */
  private java.lang.CharSequence serial;
  /** Versión del firmware */
  private java.lang.CharSequence firmware;
  /** Modelo de dispositivo */
  private java.lang.CharSequence model;
  /** Temperatura umbral crítica */
  private int temperature_threshold;
  /** Latitud en grados decimales (WGS 84 / EPSG:4326) */
  private double latitude;
  /** Longitud en grados decimales (WGS 84 / EPSG:4326) */
  private double longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Device() {}

  /**
   * All-args constructor.
   * @param id Device id
   * @param serial Numero de serie
   * @param firmware Versión del firmware
   * @param model Modelo de dispositivo
   * @param temperature_threshold Temperatura umbral crítica
   * @param latitude Latitud en grados decimales (WGS 84 / EPSG:4326)
   * @param longitude Longitud en grados decimales (WGS 84 / EPSG:4326)
   */
  public Device(java.lang.Integer id, java.lang.CharSequence serial, java.lang.CharSequence firmware, java.lang.CharSequence model, java.lang.Integer temperature_threshold, java.lang.Double latitude, java.lang.Double longitude) {
    this.id = id;
    this.serial = serial;
    this.firmware = firmware;
    this.model = model;
    this.temperature_threshold = temperature_threshold;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return serial;
    case 2: return firmware;
    case 3: return model;
    case 4: return temperature_threshold;
    case 5: return latitude;
    case 6: return longitude;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: serial = (java.lang.CharSequence)value$; break;
    case 2: firmware = (java.lang.CharSequence)value$; break;
    case 3: model = (java.lang.CharSequence)value$; break;
    case 4: temperature_threshold = (java.lang.Integer)value$; break;
    case 5: latitude = (java.lang.Double)value$; break;
    case 6: longitude = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Device id
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Device id
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'serial' field.
   * @return Numero de serie
   */
  public java.lang.CharSequence getSerial() {
    return serial;
  }


  /**
   * Sets the value of the 'serial' field.
   * Numero de serie
   * @param value the value to set.
   */
  public void setSerial(java.lang.CharSequence value) {
    this.serial = value;
  }

  /**
   * Gets the value of the 'firmware' field.
   * @return Versión del firmware
   */
  public java.lang.CharSequence getFirmware() {
    return firmware;
  }


  /**
   * Sets the value of the 'firmware' field.
   * Versión del firmware
   * @param value the value to set.
   */
  public void setFirmware(java.lang.CharSequence value) {
    this.firmware = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return Modelo de dispositivo
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * Modelo de dispositivo
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'temperature_threshold' field.
   * @return Temperatura umbral crítica
   */
  public int getTemperatureThreshold() {
    return temperature_threshold;
  }


  /**
   * Sets the value of the 'temperature_threshold' field.
   * Temperatura umbral crítica
   * @param value the value to set.
   */
  public void setTemperatureThreshold(int value) {
    this.temperature_threshold = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return Latitud en grados decimales (WGS 84 / EPSG:4326)
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * Latitud en grados decimales (WGS 84 / EPSG:4326)
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return Longitud en grados decimales (WGS 84 / EPSG:4326)
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * Longitud en grados decimales (WGS 84 / EPSG:4326)
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Creates a new Device RecordBuilder.
   * @return A new Device RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.Device.Builder newBuilder() {
    return new com.ucmmaster.kafka.data.v1.Device.Builder();
  }

  /**
   * Creates a new Device RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Device RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.Device.Builder newBuilder(com.ucmmaster.kafka.data.v1.Device.Builder other) {
    if (other == null) {
      return new com.ucmmaster.kafka.data.v1.Device.Builder();
    } else {
      return new com.ucmmaster.kafka.data.v1.Device.Builder(other);
    }
  }

  /**
   * Creates a new Device RecordBuilder by copying an existing Device instance.
   * @param other The existing instance to copy.
   * @return A new Device RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.Device.Builder newBuilder(com.ucmmaster.kafka.data.v1.Device other) {
    if (other == null) {
      return new com.ucmmaster.kafka.data.v1.Device.Builder();
    } else {
      return new com.ucmmaster.kafka.data.v1.Device.Builder(other);
    }
  }

  /**
   * RecordBuilder for Device instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Device>
    implements org.apache.avro.data.RecordBuilder<Device> {

    /** Device id */
    private int id;
    /** Numero de serie */
    private java.lang.CharSequence serial;
    /** Versión del firmware */
    private java.lang.CharSequence firmware;
    /** Modelo de dispositivo */
    private java.lang.CharSequence model;
    /** Temperatura umbral crítica */
    private int temperature_threshold;
    /** Latitud en grados decimales (WGS 84 / EPSG:4326) */
    private double latitude;
    /** Longitud en grados decimales (WGS 84 / EPSG:4326) */
    private double longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ucmmaster.kafka.data.v1.Device.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serial)) {
        this.serial = data().deepCopy(fields()[1].schema(), other.serial);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.firmware)) {
        this.firmware = data().deepCopy(fields()[2].schema(), other.firmware);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.model)) {
        this.model = data().deepCopy(fields()[3].schema(), other.model);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.temperature_threshold)) {
        this.temperature_threshold = data().deepCopy(fields()[4].schema(), other.temperature_threshold);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Device instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ucmmaster.kafka.data.v1.Device other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serial)) {
        this.serial = data().deepCopy(fields()[1].schema(), other.serial);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.firmware)) {
        this.firmware = data().deepCopy(fields()[2].schema(), other.firmware);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.model)) {
        this.model = data().deepCopy(fields()[3].schema(), other.model);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.temperature_threshold)) {
        this.temperature_threshold = data().deepCopy(fields()[4].schema(), other.temperature_threshold);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.latitude)) {
        this.latitude = data().deepCopy(fields()[5].schema(), other.latitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.longitude)) {
        this.longitude = data().deepCopy(fields()[6].schema(), other.longitude);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Device id
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Device id
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Device id
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Device id
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serial' field.
      * Numero de serie
      * @return The value.
      */
    public java.lang.CharSequence getSerial() {
      return serial;
    }


    /**
      * Sets the value of the 'serial' field.
      * Numero de serie
      * @param value The value of 'serial'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setSerial(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serial = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serial' field has been set.
      * Numero de serie
      * @return True if the 'serial' field has been set, false otherwise.
      */
    public boolean hasSerial() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serial' field.
      * Numero de serie
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearSerial() {
      serial = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'firmware' field.
      * Versión del firmware
      * @return The value.
      */
    public java.lang.CharSequence getFirmware() {
      return firmware;
    }


    /**
      * Sets the value of the 'firmware' field.
      * Versión del firmware
      * @param value The value of 'firmware'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setFirmware(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.firmware = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'firmware' field has been set.
      * Versión del firmware
      * @return True if the 'firmware' field has been set, false otherwise.
      */
    public boolean hasFirmware() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'firmware' field.
      * Versión del firmware
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearFirmware() {
      firmware = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * Modelo de dispositivo
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * Modelo de dispositivo
      * @param value The value of 'model'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.model = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * Modelo de dispositivo
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'model' field.
      * Modelo de dispositivo
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearModel() {
      model = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature_threshold' field.
      * Temperatura umbral crítica
      * @return The value.
      */
    public int getTemperatureThreshold() {
      return temperature_threshold;
    }


    /**
      * Sets the value of the 'temperature_threshold' field.
      * Temperatura umbral crítica
      * @param value The value of 'temperature_threshold'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setTemperatureThreshold(int value) {
      validate(fields()[4], value);
      this.temperature_threshold = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature_threshold' field has been set.
      * Temperatura umbral crítica
      * @return True if the 'temperature_threshold' field has been set, false otherwise.
      */
    public boolean hasTemperatureThreshold() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'temperature_threshold' field.
      * Temperatura umbral crítica
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearTemperatureThreshold() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * Latitud en grados decimales (WGS 84 / EPSG:4326)
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * Latitud en grados decimales (WGS 84 / EPSG:4326)
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setLatitude(double value) {
      validate(fields()[5], value);
      this.latitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * Latitud en grados decimales (WGS 84 / EPSG:4326)
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'latitude' field.
      * Latitud en grados decimales (WGS 84 / EPSG:4326)
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearLatitude() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * Longitud en grados decimales (WGS 84 / EPSG:4326)
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * Longitud en grados decimales (WGS 84 / EPSG:4326)
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder setLongitude(double value) {
      validate(fields()[6], value);
      this.longitude = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * Longitud en grados decimales (WGS 84 / EPSG:4326)
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'longitude' field.
      * Longitud en grados decimales (WGS 84 / EPSG:4326)
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.Device.Builder clearLongitude() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Device build() {
      try {
        Device record = new Device();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.serial = fieldSetFlags()[1] ? this.serial : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.firmware = fieldSetFlags()[2] ? this.firmware : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.model = fieldSetFlags()[3] ? this.model : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.temperature_threshold = fieldSetFlags()[4] ? this.temperature_threshold : (java.lang.Integer) defaultValue(fields()[4]);
        record.latitude = fieldSetFlags()[5] ? this.latitude : (java.lang.Double) defaultValue(fields()[5]);
        record.longitude = fieldSetFlags()[6] ? this.longitude : (java.lang.Double) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Device>
    WRITER$ = (org.apache.avro.io.DatumWriter<Device>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Device>
    READER$ = (org.apache.avro.io.DatumReader<Device>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.serial);

    out.writeString(this.firmware);

    out.writeString(this.model);

    out.writeInt(this.temperature_threshold);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.serial = in.readString(this.serial instanceof Utf8 ? (Utf8)this.serial : null);

      this.firmware = in.readString(this.firmware instanceof Utf8 ? (Utf8)this.firmware : null);

      this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);

      this.temperature_threshold = in.readInt();

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.serial = in.readString(this.serial instanceof Utf8 ? (Utf8)this.serial : null);
          break;

        case 2:
          this.firmware = in.readString(this.firmware instanceof Utf8 ? (Utf8)this.firmware : null);
          break;

        case 3:
          this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
          break;

        case 4:
          this.temperature_threshold = in.readInt();
          break;

        case 5:
          this.latitude = in.readDouble();
          break;

        case 6:
          this.longitude = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










