/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ucmmaster.kafka.data.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Alerta de temperatura */
@org.apache.avro.specific.AvroGenerated
public class TemperatureAlert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2590438424078450141L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TemperatureAlert\",\"namespace\":\"com.ucmmaster.kafka.data.v1\",\"doc\":\"Alerta de temperatura\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"temperature\",\"type\":\"int\"},{\"name\":\"temperature_threshold\",\"type\":\"int\"},{\"name\":\"excess\",\"type\":\"int\"},{\"name\":\"alert_level\",\"type\":\"string\"},{\"name\":\"alert_timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"local-timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<TemperatureAlert> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TemperatureAlert> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TemperatureAlert> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TemperatureAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TemperatureAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TemperatureAlert to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TemperatureAlert from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TemperatureAlert instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TemperatureAlert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private int temperature;
  private int temperature_threshold;
  private int excess;
  private java.lang.CharSequence alert_level;
  private java.time.LocalDateTime alert_timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TemperatureAlert() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param temperature The new value for temperature
   * @param temperature_threshold The new value for temperature_threshold
   * @param excess The new value for excess
   * @param alert_level The new value for alert_level
   * @param alert_timestamp The new value for alert_timestamp
   */
  public TemperatureAlert(java.lang.Integer id, java.lang.Integer temperature, java.lang.Integer temperature_threshold, java.lang.Integer excess, java.lang.CharSequence alert_level, java.time.LocalDateTime alert_timestamp) {
    this.id = id;
    this.temperature = temperature;
    this.temperature_threshold = temperature_threshold;
    this.excess = excess;
    this.alert_level = alert_level;
    this.alert_timestamp = alert_timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return temperature;
    case 2: return temperature_threshold;
    case 3: return excess;
    case 4: return alert_level;
    case 5: return alert_timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: temperature = (java.lang.Integer)value$; break;
    case 2: temperature_threshold = (java.lang.Integer)value$; break;
    case 3: excess = (java.lang.Integer)value$; break;
    case 4: alert_level = (java.lang.CharSequence)value$; break;
    case 5: alert_timestamp = (java.time.LocalDateTime)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return The value of the 'temperature' field.
   */
  public int getTemperature() {
    return temperature;
  }


  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(int value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'temperature_threshold' field.
   * @return The value of the 'temperature_threshold' field.
   */
  public int getTemperatureThreshold() {
    return temperature_threshold;
  }


  /**
   * Sets the value of the 'temperature_threshold' field.
   * @param value the value to set.
   */
  public void setTemperatureThreshold(int value) {
    this.temperature_threshold = value;
  }

  /**
   * Gets the value of the 'excess' field.
   * @return The value of the 'excess' field.
   */
  public int getExcess() {
    return excess;
  }


  /**
   * Sets the value of the 'excess' field.
   * @param value the value to set.
   */
  public void setExcess(int value) {
    this.excess = value;
  }

  /**
   * Gets the value of the 'alert_level' field.
   * @return The value of the 'alert_level' field.
   */
  public java.lang.CharSequence getAlertLevel() {
    return alert_level;
  }


  /**
   * Sets the value of the 'alert_level' field.
   * @param value the value to set.
   */
  public void setAlertLevel(java.lang.CharSequence value) {
    this.alert_level = value;
  }

  /**
   * Gets the value of the 'alert_timestamp' field.
   * @return The value of the 'alert_timestamp' field.
   */
  public java.time.LocalDateTime getAlertTimestamp() {
    return alert_timestamp;
  }


  /**
   * Sets the value of the 'alert_timestamp' field.
   * @param value the value to set.
   */
  public void setAlertTimestamp(java.time.LocalDateTime value) {
    this.alert_timestamp = value;
  }

  /**
   * Creates a new TemperatureAlert RecordBuilder.
   * @return A new TemperatureAlert RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder newBuilder() {
    return new com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder();
  }

  /**
   * Creates a new TemperatureAlert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TemperatureAlert RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder newBuilder(com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder other) {
    if (other == null) {
      return new com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder();
    } else {
      return new com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder(other);
    }
  }

  /**
   * Creates a new TemperatureAlert RecordBuilder by copying an existing TemperatureAlert instance.
   * @param other The existing instance to copy.
   * @return A new TemperatureAlert RecordBuilder
   */
  public static com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder newBuilder(com.ucmmaster.kafka.data.v1.TemperatureAlert other) {
    if (other == null) {
      return new com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder();
    } else {
      return new com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder(other);
    }
  }

  /**
   * RecordBuilder for TemperatureAlert instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TemperatureAlert>
    implements org.apache.avro.data.RecordBuilder<TemperatureAlert> {

    private int id;
    private int temperature;
    private int temperature_threshold;
    private int excess;
    private java.lang.CharSequence alert_level;
    private java.time.LocalDateTime alert_timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.temperature)) {
        this.temperature = data().deepCopy(fields()[1].schema(), other.temperature);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.temperature_threshold)) {
        this.temperature_threshold = data().deepCopy(fields()[2].schema(), other.temperature_threshold);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.excess)) {
        this.excess = data().deepCopy(fields()[3].schema(), other.excess);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.alert_level)) {
        this.alert_level = data().deepCopy(fields()[4].schema(), other.alert_level);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.alert_timestamp)) {
        this.alert_timestamp = data().deepCopy(fields()[5].schema(), other.alert_timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing TemperatureAlert instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ucmmaster.kafka.data.v1.TemperatureAlert other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temperature)) {
        this.temperature = data().deepCopy(fields()[1].schema(), other.temperature);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature_threshold)) {
        this.temperature_threshold = data().deepCopy(fields()[2].schema(), other.temperature_threshold);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.excess)) {
        this.excess = data().deepCopy(fields()[3].schema(), other.excess);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.alert_level)) {
        this.alert_level = data().deepCopy(fields()[4].schema(), other.alert_level);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.alert_timestamp)) {
        this.alert_timestamp = data().deepCopy(fields()[5].schema(), other.alert_timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * @return The value.
      */
    public int getTemperature() {
      return temperature;
    }


    /**
      * Sets the value of the 'temperature' field.
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setTemperature(int value) {
      validate(fields()[1], value);
      this.temperature = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'temperature' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearTemperature() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature_threshold' field.
      * @return The value.
      */
    public int getTemperatureThreshold() {
      return temperature_threshold;
    }


    /**
      * Sets the value of the 'temperature_threshold' field.
      * @param value The value of 'temperature_threshold'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setTemperatureThreshold(int value) {
      validate(fields()[2], value);
      this.temperature_threshold = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature_threshold' field has been set.
      * @return True if the 'temperature_threshold' field has been set, false otherwise.
      */
    public boolean hasTemperatureThreshold() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'temperature_threshold' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearTemperatureThreshold() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'excess' field.
      * @return The value.
      */
    public int getExcess() {
      return excess;
    }


    /**
      * Sets the value of the 'excess' field.
      * @param value The value of 'excess'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setExcess(int value) {
      validate(fields()[3], value);
      this.excess = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'excess' field has been set.
      * @return True if the 'excess' field has been set, false otherwise.
      */
    public boolean hasExcess() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'excess' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearExcess() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_level' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlertLevel() {
      return alert_level;
    }


    /**
      * Sets the value of the 'alert_level' field.
      * @param value The value of 'alert_level'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setAlertLevel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.alert_level = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_level' field has been set.
      * @return True if the 'alert_level' field has been set, false otherwise.
      */
    public boolean hasAlertLevel() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'alert_level' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearAlertLevel() {
      alert_level = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_timestamp' field.
      * @return The value.
      */
    public java.time.LocalDateTime getAlertTimestamp() {
      return alert_timestamp;
    }


    /**
      * Sets the value of the 'alert_timestamp' field.
      * @param value The value of 'alert_timestamp'.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder setAlertTimestamp(java.time.LocalDateTime value) {
      validate(fields()[5], value);
      this.alert_timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_timestamp' field has been set.
      * @return True if the 'alert_timestamp' field has been set, false otherwise.
      */
    public boolean hasAlertTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'alert_timestamp' field.
      * @return This builder.
      */
    public com.ucmmaster.kafka.data.v1.TemperatureAlert.Builder clearAlertTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TemperatureAlert build() {
      try {
        TemperatureAlert record = new TemperatureAlert();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.temperature = fieldSetFlags()[1] ? this.temperature : (java.lang.Integer) defaultValue(fields()[1]);
        record.temperature_threshold = fieldSetFlags()[2] ? this.temperature_threshold : (java.lang.Integer) defaultValue(fields()[2]);
        record.excess = fieldSetFlags()[3] ? this.excess : (java.lang.Integer) defaultValue(fields()[3]);
        record.alert_level = fieldSetFlags()[4] ? this.alert_level : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.alert_timestamp = fieldSetFlags()[5] ? this.alert_timestamp : (java.time.LocalDateTime) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TemperatureAlert>
    WRITER$ = (org.apache.avro.io.DatumWriter<TemperatureAlert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TemperatureAlert>
    READER$ = (org.apache.avro.io.DatumReader<TemperatureAlert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










